### ISSUE TITLE
Testimonial image not in the right place

### ISSUE THREAD

**Issue by StefanSelfTaught** [cruip/tailwind-landing-page-template#1]
When I open the website in mobile and then refreshing the page the testimonial image moves up.

![image](https://user-images.githubusercontent.com/43994418/96371684-9a21a080-116b-11eb-8ae4-72af6d00ea36.png)

**Comment by pasqualevitiello** [comment]
Thank you for reporting, issue is fixed with https://github.com/cruip/tailwind-landing-page-template/commit/7e1cf003f3a7bdda248cb99377955c438a50a7dd
