### ISSUE TITLE
Seo

### ISSUE THREAD

**Issue by neondeex** [cruip/tailwind-landing-page-template#13]
Hi how can i add SEO support to this website?

**Comment by Daniel-Brai** [comment]
The hard way: You could probably write the meta tags needed for SEO in the`index.html` of the base directory then build using `npm run build` . Then use a node server to serve the `dist` folder as static assets. Problem with this is that everything want to make a change you have to build react app again and change the `dist` folder in the node server.

The easy way: Just port it to Next JS and using the inbuilt SEO stuff.
