### ISSUE TITLE
App is blank once I build it

### ISSUE THREAD

**Issue by RayanAbid** [cruip/tailwind-landing-page-template#19]
Hi! I've been trying to build the app using `` npm run build `` the build is created successfully no errors at all but when I try to open the link the page is blank. 

<img width="1440" alt="Screen Shot 2022-12-28 at 2 05 44 AM" src="https://user-images.githubusercontent.com/68749736/209722277-27b45b5f-6235-43c6-854e-b4b5e043dd12.png">

This is the only error that I get. Any ideas on what might be causing this? 

It works fine on dev mode.

**Comment by pasqualevitiello** [comment]
I am unable to replicate the issue. I've just cloned the repository, installed the dependencies with `npm i` and built the app with `npm run build`. Did you make some changes to the template maybe?

**Comment by farfamahar** [comment]
I also get a similar problem. It's blank on mobile. Works fine on desktop, but if I resize the window to a mobile layout in the inspector and refresh the page, the layout is blank there too.

Edit- I believe I've isolated the issue to data-aos="zoom-y-out" in the HeroHome component. AOS is disabled on mobile which prevents anything from showing up at all.
Removing the disabled property from AOS.init fixed it.
