### ISSUE TITLE
breaking error - Module parse failed: Bad character escape sequence (2:97) 

### ISSUE THREAD

**Issue by ChrispyCodes** [cruip/tailwind-landing-page-template#24]
"use client" in header.tsx is causing issue

File was processed with these loaders:
 * ./node_modules/next/dist/build/webpack/loaders/next-flight-loader/index.js
 * ./node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
You may need an additional loader to handle the result of these loaders.
| import { createProxy } from "next/dist/build/webpack/loaders/next-flight-loader/module-proxy"

you can update next js to 13.3.1-canary.4

npm

npm i next@13.3.1-canary.4

yarn

yarn add next@13.3.1-canary.4

**Comment by collasanta** [comment]
npm i next@13.3.1-canary.4
