### ISSUE TITLE
Failed To Compile

### ISSUE THREAD

**Issue by Andreyhuey** [cruip/tailwind-landing-page-template#25]
Failed to compile
./components/ui/header.tsx
Module parse failed: Bad character escape sequence (2:123)
| import { createProxy } from "next/dist/build/webpack/loaders/next-flight-loader/module-proxy"
> const proxy = createProxy("C:\Users\HP\Desktop\dev\Tech-Stack\CSS\Tailwind\Tailwind-landing-page\open-pro-next\components\ui\header.tsx")
| 
| // Accessing the __esModule property and exporting $$typeof are required here.
This error occurred during the build process and can only be dismissed by fixing the error..

**Comment by collasanta** [comment]
npm i next@13.3.1-canary.4
