### ISSUE TITLE
Is it free or Priced Template

### ISSUE THREAD

**Issue by A5H1Q** [cruip/tailwind-landing-page-template#3]
firstly, Awesome work guys..  

when exploring this template in [cruip](https://cruip.com/demos/simple/), it shows that you've to buy this item, but this repo states otherwise. so is it really free and open source?

**Comment by pasqualevitiello** [comment]
Hello, the template on Cruip.com is premium and it includes more pages and components. Here is the difference:
- Free version (demo): https://simple.cruip.com/
- Premium version (demo): https://preview.cruip.com/simple/
