### ISSUE TITLE
Query About Placement of Google Analytics Tag

### ISSUE THREAD

**Issue by yachty66** [cruip/tailwind-landing-page-template#39]
Hello,

I'm using the website template and I'm looking to integrate Google Analytics. Could you please advise on where exactly should the Google Analytics tag be placed in the template?

Thanks for your help!

**Comment by dellamora** [comment]
Hi,

The Google Analytics tag should be in the layout file, more precisely below the <head> tag, within the <body>. 

Try to put it on line 31

 ![image](https://github.com/cruip/tailwind-landing-page-template/assets/62533297/7f55364d-38b8-44e5-96ba-49ca4a1eadb7)

**Comment by dellamora** [comment]
can someone assign this issue to me? ^^
