### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by japrozs** [cruip/tailwind-landing-page-template#6]
First of all, if I add more than 2 links in the navbar, will it automatically become responsive ?

If not, can you please make the navbar responsive like you did in the `open-react-template` repository

**Comment by pasqualevitiello** [comment]
Hey there, unfortunately this template does not come with a mobile menu. You might want to check out the premium version, that includes a responsive navigation, and more pages and components: https://cruip.com/demos/simple/

Best, P.
